title: Hello, world! I'm Tumelo Mogano.
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/tumeloontech" # the subpath of your site, e.g. /blog
url: "ibelievesintumelo.github.io" # the base hostname & protocol for your site
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tumelo Mogano # add your name
author-img: tumelo_mogano.jpg # add your photo
about-author: I am a student and software developer that started out as an electrician and now venturing into tech. # add description
social-twitter: mo_aforika # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: iBelievesInTumelo # add your Github handle
social-linkedin: tumelomogano # add your Linkedin handle
social-email: tumelo.mogano@gmail.com # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
